// web-opforms-react/src/components/ShowForm.jsx
import { useContext, useEffect, useState } from "react";
import { FormContext } from "../context/FormContext";
import { useNavigate, NavLink } from "react-router-dom";

export const ShowForm = ({ formSelected, handlerCloseForm }) => {
    const { initialOPForm, getData, getForm, updateData, createData } = useContext(FormContext);
    const navigate = useNavigate();
    const [oPForm, setOPForm] = useState(initialOPForm);
    const { formcode, formId } = oPForm;
    const [oid, setOid] = useState('');
    var buildState;

    useEffect(() => {
        setOPForm({
            ...formSelected
        });
        showForm(formSelected.formcode, formSelected.formId,)
    }, [formSelected]);

    const showForm = async (formcode, formId) => {
        if (formcode && formcode.length > 0) {
            window.formId = formcode;
            if (formId != null && formId.length > 0) {
                const responsedata = await getData(formcode, formId);
                const resp = responsedata.data;
                if (!resp.i18nJson) {
                    resp.i18nJson = null
                }
                if (resp?.datasources) {
                    window.ds = resp.datasources
                }
                window.Formio.createForm(
                    document.getElementById('formdiv'),
                    resp.schema, resp.i18nJson
                ).then(function (build) {
                    buildState = build;
                    buildState.submission = {
                        data: resp.data[0],
                    };

                    buildState.on('redirect', function (redirecto) {
                        navigate(`/forms/formshow/${redirecto.formcode}/${redirectto.dataoid}`);
                    })

                    buildState.on("submit", function (submission) {
                        updateData(
                            formcode,
                            formId,
                            submission
                        )
                            .then(function () {
                                buildState.emit("submitDone", submission);
                            })
                            .catch(function (error) {
                                console.log(error);
                                buildState.emit('submitError', error);
                            });
                    });
                });
            } else {

                //show existing form without data

                const responsedata = await getForm(formcode);

                var response = responsedata.data;
                if (!response.i18nJson) {
                    response.i18nJson = null
                }
                if (response?.datasources) {
                    window.ds = response.datasources
                }
                window.Formio.createForm(
                    document.getElementById('formdiv'),
                    JSON.parse(response.jsonSchema), JSON.parse(response.i18nJson)
                ).then(function (build) {
                    buildState = build;
                    buildState.on('redirect', function (redirecto) {
                        navigate(`/forms/formshow/${redirecto.formcode}/${redirectto.dataoid}`);
                    })

                    buildState.on("submit", function (submission) {

                        createData(
                            formcode,
                            submission
                        )
                            .then(function (data) {
                                if (data.ids && data.ids.length > 0) {
                                    window.resultId = data.ids[0]
                                }
                                buildState.emit('submitDone', submission)
                            })
                            .catch(function (error) {
                                buildState.emit('submitError', error)
                                console.log(error)
                            });
                    });
                });
            }
        }
    }


    const onCloseForm = () => {
        handlerCloseForm();
        setOPForm(initialOPForm);
    }
    return (
        <div>
            <label>You can fill the record identifier to load the form with the record data</label>
            <br></br>
            <input value={oid} onChange={e => setOid(e.target.value)}
            /><br></br><br></br>
            <NavLink className={'btn btn-primary btn-sm'}
                to={`/forms/formshow/${formcode}/${oid}`} >
                Show Form
            </NavLink>
            <NavLink className={'btn btn-link btn-sm'}
                to={'/forms'} >
                Back to List
            </NavLink>
            <hr class="hr" />

            <div id="formdiv"></div>
        </div>
    )
}

// web-opforms-angular/src/app/showform/showform.component.ts
import { Component, Input, SimpleChanges, inject } from '@angular/core';
import { OnesaitplatformservicesService } from '../onesaitplatformservices.service';
import { FormsModule } from '@angular/forms';
import {MatInputModule} from '@angular/material/input';
import {MatFormFieldModule} from '@angular/material/form-field';
import { MatDividerModule } from '@angular/material/divider';
import {MatButtonModule} from '@angular/material/button';

@Component({
  selector: 'app-showform',
  standalone: true,
  imports: [FormsModule,MatInputModule,MatDividerModule,MatButtonModule,MatFormFieldModule],
  templateUrl: './showform.component.html',
  styleUrl: './showform.component.css'
})
export class ShowformComponent {
  private onesaitplatformservicesService = inject(OnesaitplatformservicesService);
  oid='';
  private build: any;
  @Input() fcode ='';


  constructor() {
  }

  ngOnChanges(changes: SimpleChanges) {
    console.log(changes)
    if(this.fcode && this.fcode.length>0){
      this.redirectTo({formcode:this.fcode,dataoid:null});
    }
  }

  redirectTo(data:any){
    if((<any>document.getElementById('formdiv')))
      { 
        (<any>document.getElementById('formdiv')).innerHTML = "";
      }
    this.showForm(data.formcode,data.dataoid);
  }

  showForm(formcode: string, formId: string) {
    var that = this;
    if (formcode && formcode.length > 0) {
      (<any>global).formId = formcode;
      //show existing form with data
      if (formId && formId.length > 0) {
        this.onesaitplatformservicesService.getData(formcode, formId)?.subscribe({
          next: resp => {
            if (!(<any>resp).i18nJson) {
              (<any>resp).i18nJson = null
            }
            if ((<any>resp)?.datasources) {
              (<any>global).ds = (<any>resp).datasources;
            }
            (<any>global).Formio.createForm(
              document.getElementById('formdiv'),
              (<any>resp).schema, (<any>resp).i18nJson
            ).then(function (build: any) {
              that.build = build;
              that.build.submission = {
                data: (<any>resp).data[0],
              };

              that.build.on('redirect', function (redirecto: any) {
                that.redirectTo(redirecto)
              })

              that.build.on("submit", function (submission: any) {
                that.onesaitplatformservicesService.updateData(formcode, formId, submission)?.subscribe({
                  next: response => {
                    that.build.emit("submitDone", submission);
                  }, // success path
                  error: error => {
                    console.log(error);
                    that.build.emit('submitError', error);
                  }

                });

              });
            });

          }, // success path
          error: error => console.log(error), // error path
        });

      }
      else {
        this.onesaitplatformservicesService.getForm(formcode)?.subscribe({
          next: resp => {
            if (!(<any>resp).i18nJson) {
              (<any>resp).i18nJson = null
            }
            if ((<any>resp)?.datasources) {
              (<any>global).ds = (<any>resp).datasources;
            }
            (<any>global).Formio.createForm(
              document.getElementById('formdiv'),
              JSON.parse( (<any>resp).jsonSchema), JSON.parse((<any>resp).i18nJson)
            ).then(function (build: any) {
              that.build = build;
             

              that.build.on('redirect', function (redirecto: any) {
                that.redirectTo(redirecto)
              })

              that.build.on("submit", function (submission: any) {
                that.onesaitplatformservicesService.createData(formcode, submission)?.subscribe({
                  next: response => {
                    if ((<any>response).ids && (<any>response).ids.length > 0) {
                      (<any>global).resultId = (<any>response).ids[0]
                    }
                    that.build.emit("submitDone", submission);
                  }, // success path
                  error: error => {
                    console.log(error);
                    that.build.emit('submitError', error);
                  }

                });

              });
            });

          }, // success path
          error: error => console.log(error), // error path
        });
      }

    }
  }
}

<div class="exampleform">
<br>
    <mat-label>You can fill the record identifier to load the form with the record data</mat-label><br>
<br>
    <mat-form-field>
        <input type="text"  matInput [(ngModel)]="oid" id="oid"><br>
    </mat-form-field>
    <br><button mat-button color="primary"    (click)="showForm('helsinkicreate-developer',this.oid)">Show</button> 
<br>
    <mat-divider></mat-divider>
</div>
<div id="formdiv"></div>
